import { useCallback, useEffect, useRef, useState } from "react";

export function useAutoScroll<T extends unknown[]>(dependencies: T) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const [shouldShowButton, setShouldShowButton] = useState(false);

  // Core lock state
  const isLockedToBottom = useRef(true);
  const isProgrammaticSmoothScroll = useRef(false);
  const smoothScrollTimer = useRef<number>(0);

  // Check if currently at bottom
  const checkIsAtBottom = useCallback((div: HTMLElement) => {
    const threshold = 30;
    return div.scrollHeight - div.scrollTop - div.clientHeight <= threshold;
  }, []);

  // Instant scroll if locked
  const scrollIfLocked = useCallback(() => {
    const div = scrollRef.current;
    if (!div || !isLockedToBottom.current) return;
    div.scrollTop = div.scrollHeight;
  }, []);

  // User-invoked or programmatic scroll to bottom
  const scrollToBottom = useCallback((behavior: ScrollBehavior = "auto") => {
    const div = scrollRef.current;
    if (!div) return;

    isLockedToBottom.current = true;
    setShouldShowButton(false);

    // Ignore native scroll events while this programmatic scroll is occurring
    isProgrammaticSmoothScroll.current = true;
    clearTimeout(smoothScrollTimer.current);

    if (behavior === "smooth") {
      smoothScrollTimer.current = window.setTimeout(() => {
        isProgrammaticSmoothScroll.current = false;
      }, 1500); // Wait for smooth scroll animation to finish
      div.scrollTo({ top: div.scrollHeight, behavior: "smooth" });
    } else {
      // Jump instantly
      div.scrollTop = div.scrollHeight;
      requestAnimationFrame(() => {
        isProgrammaticSmoothScroll.current = false;
      });
    }
  }, []);

  // Let browser physics rule the state naturally
  const handleScroll = useCallback(() => {
    const div = scrollRef.current;
    if (!div) return;

    // Ignore scroll events generated by our scrollToBottom animation
    if (isProgrammaticSmoothScroll.current) return;

    const atBottom = checkIsAtBottom(div);
    isLockedToBottom.current = atBottom;
    setShouldShowButton(!atBottom);
  }, [checkIsAtBottom]);

  // Pre-emptive scroll intents: The moment the user tries to scroll up, we break the lock
  // This happens *before* the native scroll registers, so we don't fight the LLM's scrollIfLocked.
  useEffect(() => {
    const div = scrollRef.current;
    if (!div) return;

    const handleWheel = (e: WheelEvent) => {
      if (e.deltaY < 0) {
        isLockedToBottom.current = false;
        isProgrammaticSmoothScroll.current = false;
        setShouldShowButton(true);
      }
    };

    let startY = 0;
    const handleTouchStart = (e: TouchEvent) => {
      startY = e.touches[0].clientY;
    };
    const handleTouchMove = (e: TouchEvent) => {
      if (startY && e.touches[0].clientY > startY) {
        isLockedToBottom.current = false;
        isProgrammaticSmoothScroll.current = false;
        setShouldShowButton(true);
      }
    };

    div.addEventListener("wheel", handleWheel, { passive: true });
    div.addEventListener("touchstart", handleTouchStart, { passive: true });
    div.addEventListener("touchmove", handleTouchMove, { passive: true });

    return () => {
      div.removeEventListener("wheel", handleWheel);
      div.removeEventListener("touchstart", handleTouchStart);
      div.removeEventListener("touchmove", handleTouchMove);
    };
  }, []);

  // DOM observer for new nodes/images
  useEffect(() => {
    const div = scrollRef.current;
    if (!div) return;

    const onContentGrow = () => {
      if (isLockedToBottom.current) {
        // use auto behavior to keep following fast output responsive
        div.scrollTop = div.scrollHeight;
      }
    };

    const resizeObserver = new ResizeObserver(onContentGrow);
    const mutationObserver = new MutationObserver(onContentGrow);

    resizeObserver.observe(div);
    mutationObserver.observe(div, {
      childList: true,
      subtree: true,
    });

    return () => {
      resizeObserver.disconnect();
      mutationObserver.disconnect();
    };
  }, []);

  // Redux/React content change dependencies
  useEffect(() => {
    scrollIfLocked();
  }, [...dependencies, scrollIfLocked]);

  return {
    scrollRef,
    handleScroll,
    scrollToBottom,
    showScrollButton: shouldShowButton,
  };
}
